#base image 
FROM python:3.7-alpine

#working directory
WORKDIR /src

#adding the files to the working directory
ADD app.py /src/
ADD userdata.py /src/
ADD requirements.txt /src/

#set the environment variables used by flask command
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

#install the requirements
RUN pip install -r requirements.txt

#expose the port
EXPOSE 5000

#set default command for the container to flask run
CMD ["flask", "run"]

